name: 'Partior - Check if artifact already promoted'
description: 'Check artifactory if artifact has been promoted'
inputs:
  source-artifact-full-path:  
    description: 'Full artifactory path to source artifact'
    required: true
    default: ''

  release-artifact-full-path:
    description: 'Full artifactory path to target release artifact'
    required: true
    default: ''

  jfrog-token:  
    description: 'Jfrog token'
    required: true
    default: ''

outputs:
  qualified:
    description: "Return check result if artifact can be promoted. true/false"
    value: ${{ steps.promotion.outputs.valid-result }}

runs:
  using: "composite"

  steps:
    - name: Setup jfrog
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ENV_1: ${{ inputs.jfrog-token }}

    - name: Check if source and target is identical
      id: get-properties
      env:
        SRC_ARTIFACT_PROP_JSON_FILE: src-artifact-prop-file
        RELEASE_ARTIFACT_PROP_JSON_FILE: release-artifact-prop-file
      run: |
        set +e
        validResult=false
        echo ::set-output name=valid-result::${validResult}
        function failIfEmpty() {
            local inputKey="$1"
            local inputKeyValue=${!inputKey}
            if [[ -z "$inputKeyValue" ]]; then
                echo "[ERROR] Key is undefined: $inputKey. Verify if the artifact has been deployed to promotion prerequisite env properly"
                exit 1
            fi
        }

        ${{ github.action_path }}/../../scripts/generic-curl-get-artifact-meta.sh \
            "${{ inputs.source-artifact-full-path }}" \
            "properties" \
            "${{ env.SRC_ARTIFACT_PROP_JSON_FILE }}"
        if [[ $? -ne 0 ]]; then
            echo "[ERROR] Unable to find source artifact: ${{ inputs.source-artifact-full-path }}"
            exit 1
        fi
        PROMO_QL_FLAG=$(cat ${SRC_ARTIFACT_PROP_JSON_FILE} | jq -r '.properties."promotion.qualified"[]')
        PROMO_QL_DEPLOYED_ENV=$(cat ${SRC_ARTIFACT_PROP_JSON_FILE} | jq -r '.properties."promotion.prerequisite.deployed.env"[]')
        PROMO_QL_DEPLOYED_TIMESTAMP=$(cat ${SRC_ARTIFACT_PROP_JSON_FILE} | jq -r '.properties."promotion.prerequisite.deployed.timestamp"[]')

        ## Throw error if not set
        failIfEmpty "PROMO_QL_FLAG"
        failIfEmpty "PROMO_QL_DEPLOYED_ENV"
        failIfEmpty "PROMO_QL_DEPLOYED_TIMESTAMP"

        if [[ "$PROMO_QL_FLAG" != "true" ]]; then
            echo "[ERROR] Promotion qualification flag [promotion.qualified] is false. Verify if the artifact has been deployed to promotion prerequisite env properly"
            exit 1
        fi
        validResult=true
        echo ::set-output name=valid-result::${validResult}
      shell: bash


    - name: Set status
      id: promotion
      run: |
        if [[ "${{ steps.get-properties.outputs.valid-result }}" == 'true' ]]; then
            echo ::set-output name=valid-result::'true'
        else
            echo ::set-output name=valid-result::'false'
        fi
      shell: bash  
        
    - run: echo [INFO] Done checking...
      shell: bash

