name: 'Partior - Override yaml file'
description: 'Override target yaml config custom value'
inputs:
  source-yaml-file:  
    description: 'Path to source YAML file'
    required: true
    default: 'default-config.yaml'
  target-yaml-file:  
    description: 'Path to target YAML file to be overwritten'
    required: true
    default: 'default-target-config.yaml'
  query-path:  
    description: 'YAML query path'
    required: true
    default: ''
  write-query-path:  
    description: 'YAML query path to be overwritten'
    required: true
    default: ''
  output-file:  
    description: 'Custom path of the output file'
    required: false
    default: 'NIL'
  upload:  
    description: 'Flag to indicate if require to upload the file'
    required: false
    default: false
outputs:
  generated-filename:
    description: "Filename of the converted config script"
    value: ${{ inputs.output-file }}
runs:
  using: "composite"
  steps:
    - name: get outfile file
      id: output-file
      run: |
        outputFile=${{ inputs.output-file }}
        if [[ "$outputFile" == "NIL" ]]; then
          outputFile=${{ inputs.target-yaml-file }}
        fi
        echo filename=${outputFile} >> $GITHUB_OUTPUT
      shell: bash

    - name: convert yaml to props config
      run: ${{ github.action_path }}/../../scripts/generic-override-yaml-conf.sh "${{ inputs.source-yaml-file }}" "${{ inputs.target-yaml-file }}" "${{ inputs.query-path }}" "${{ inputs.write-query-path }}" "${{ steps.output-file.outputs.filename }}"
      shell: bash

    - name: upload yaml config
      uses: actions/upload-artifact@v3
      if: inputs.upload == 'true'
      with:
        name: ${{ steps.output-file.outputs.filename }}
        path: ${{ steps.output-file.outputs.filename }}
        if-no-files-found: error
        retention-days: 1
        
    - run: echo Done creating yaml config file...
      shell: bash
