
name: 'Partior - Check if artifact already promoted'
description: 'Check artifactory if artifact has been promoted'
inputs:
  source-artifact-full-path:  
    description: 'Full artifactory path to source artifact'
    required: true
    default: ''

  release-artifact-full-path:
    description: 'Full artifactory path to target release artifact'
    required: true
    default: ''

  jfrog-token:  
    description: 'Jfrog token'
    required: true
    default: ''

  jira-username:
    description: 'Jira username'
    required: true
    default: ''
 
  jira-token:
    description: 'Jira password'
    required: true
    default: ''

  final-artifact-source-version:
    description: 'Final artifact source version'
    required: true
    default: ''

  final-artifact-release-version:
    description: 'Final artifact release version'
    required: true
    default: ''

  jira-base-url:
    description: 'Jira base url'
    required: false
    default: 'https://partior.atlassian.net'

  jira-version-identifier:
    description: 'Artifact version identifier'
    required: true
    default: ''

  jira-project-key:
    description: 'Jira project key'
    required: true
    default: ''

runs:
  using: "composite"

  steps:
    - name: Setup jfrog
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ENV_1: ${{ inputs.jfrog-token }}

    - name: Promote artifact and set properties
      run: |
        currentTimestamp=$(date +%s)
        echo "[INFO] Promoting from ${{ inputs.source-artifact-full-path }} to ${{ inputs.release-artifact-full-path }}"
   #     jfrog rt cp ${{ inputs.source-artifact-full-path }} ${{ inputs.release-artifact-full-path }} --flat=true
   #     jfrog rt sp ${{ inputs.source-artifact-full-path }} "promotion.promoted.stage=release;promotion.promoted.timestamp=${currentTimestamp};promotion.promoted.to=${{ inputs.release-artifact-full-path }}"
   #     jfrog rt sp ${{ inputs.release-artifact-full-path }} "promotion.promoted.stage=release;promotion.promoted.timestamp=${currentTimestamp};promotion.promoted.from=${{ inputs.source-artifact-full-path }}"
      shell: bash

    - name: Promote artifact version in jira  
      run: |
       ${{ github.action_path }}/../../scripts/generic-promote-version.sh "${{ inputs.jira-username }}" \
          "${{ inputs.jira-token }}" \
          "${{ inputs.jira-base-url }}" \
          "${{ inputs.final-artifact-source-version }}" \
          "${{ inputs.final-artifact-release-version }}" \
          "${{ inputs.jira-version-identifier }}" \
          "${{ inputs.jira-project-key }}"
      shell: bash

    - run: echo [INFO] Done promotion...
      shell: bash
