name: 'Partior - Check if artifact already promoted'
description: 'Check artifactory if artifact has been promoted'
inputs:
  source-artifact-full-path:  
    description: 'Full artifactory path to source artifact'
    required: true
    default: ''

  release-artifact-full-path:
    description: 'Full artifactory path to target release artifact'
    required: true
    default: ''

  jfrog-token:  
    description: 'Jfrog token'
    required: true
    default: ''


runs:
  using: "composite"

  steps:
    - name: Setup jfrog
      uses: jfrog/setup-jfrog-cli@v2
      env:
        JF_ENV_1: ${{ inputs.jfrog-token }}

    - name: Promote artifact and set properties
      run: |
        currentTimestamp=$(date +%s)
        echo "[INFO] Promoting from ${{ inputs.source-artifact-full-path }} to ${{ inputs.release-artifact-full-path }}"
        jfrog rt cp ${{ inputs.source-artifact-full-path }} ${{ inputs.release-artifact-full-path }}
        jfrog rt sp ${{ inputs.source-artifact-full-path }} "promotion.promoted.stage=release;promotion.promoted.timestamp=${currentTimestamp};promoted.to=${{ inputs.release-artifact-full-path }}"
        jfrog rt sp ${{ inputs.source-artifact-full-path }} "promotion.promoted.stage=release;promotion.promoted.timestamp=${currentTimestamp};promoted.from=${{ inputs.source-artifact-full-path }}"
      shell: bash

        
    - run: echo [INFO] Done promotion...
      shell: bash

