
name: 'Partior - Check if artifact already promoted'
description: 'Check artifactory if artifact has been promoted'
inputs:
  source-artifact-full-path:  
    description: 'Full artifactory path to source artifact'
    required: true
    default: ''

  release-artifact-full-path:
    description: 'Full artifactory path to target release artifact'
    required: true
    default: ''

  jfrog-token:  
    description: 'Jfrog token'
    required: true
    default: ''

  jira-username:
    description: 'Jira username'
    required: false
    default: ''
 
  jira-token:
    description: 'Jira token'
    required: false
    default: ''

  source-artifact-version:
    description: 'Final artifact source version. If not specified, will derived from "source-artifact-full-path"'
    required: false
    default: ''

  release-artifact-version:
    description: 'Final artifact release version. If not specified, will derived from "release-artifact-full-path"'
    required: false
    default: ''

  jira-base-url:
    description: 'Jira base url'
    required: false
    default: 'https://partior.atlassian.net'

  jira-version-identifier:
    description: 'Artifact version identifier'
    required: false
    default: ''

  jira-project-key:
    description: 'Jira project key'
    required: false
    default: ''

runs:
  using: "composite"

  steps:
    - name: Setup jfrog
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_ENV_1: ${{ inputs.jfrog-token }}

    - name: Promote artifact and set properties
      run: |
        currentTimestamp=$(date +%s)
        echo "[INFO] Promoting from ${{ inputs.source-artifact-full-path }} to ${{ inputs.release-artifact-full-path }}"
        jfrog rt cp ${{ inputs.source-artifact-full-path }} ${{ inputs.release-artifact-full-path }} --flat=true
        jfrog rt sp ${{ inputs.source-artifact-full-path }} "promotion.promoted.stage=release;promotion.promoted.timestamp=${currentTimestamp};promotion.promoted.to=${{ inputs.release-artifact-full-path }}"
        jfrog rt sp ${{ inputs.release-artifact-full-path }} "promotion.promoted.stage=release;promotion.promoted.timestamp=${currentTimestamp};promotion.promoted.from=${{ inputs.source-artifact-full-path }}"
      shell: bash

    - name: Validate input parameters
      run: |
        set +e
        if [[ ! -z "${{ inputs.jira-project-key }}" ]]; then
          if [[ -z "${{ inputs.jira-version-identifier }}" ]] || [[ -z "${{ inputs.jira-username }}" ]] || [[ -z "${{ inputs.jira-token }}" ]]; then
            echo "[ERROR] Jira version identifier, username and password/token must be specified."
            exit 1
          fi
        fi
        SOURCE_ARTIFACT_VERSION=${{ inputs.source-artifact-version }}
        RELEASE_ARTIFACT_VERSION=${{ inputs.release-artifact-version }}
        if [[ -z "${SOURCE_ARTIFACT_VERSION}" ]]; then
          sourceArtifactFile=$(basename ${{ inputs.source-artifact-full-path }})
          releaseArtifactFile=$(basename ${{ inputs.release-artifact-full-path }})
          SOURCE_ARTIFACT_VERSION="${sourceArtifactFile%.*}"
          RELEASE_ARTIFACT_VERSION="${releaseArtifactFile%.*}"
        fi
        echo "SOURCE_ARTIFACT_VERSION=${SOURCE_ARTIFACT_VERSION}" >> $GITHUB_ENV
        echo "RELEASE_ARTIFACT_VERSION=${RELEASE_ARTIFACT_VERSION}" >> $GITHUB_ENV
      shell: bash

    - name: Promote artifact version in jira  
      if: inputs.jira-project-key != ''
      run: |
        ${{ github.action_path }}/../../scripts/generic-promote-version-in-jira.sh "${{ inputs.jira-username }}" \
          "${{ inputs.jira-token }}" \
          "${{ inputs.jira-base-url }}" \
          "${SOURCE_ARTIFACT_VERSION}" \
          "${RELEASE_ARTIFACT_VERSION}" \
          "${{ inputs.jira-version-identifier }}" \
          "${{ inputs.jira-project-key }}"
      shell: bash

    - run: echo [INFO] Done promotion...
      shell: bash
