## For this action to work, it has to be executed after a matrix job where it will generate another sequence item list to be executed as sub matrix.
## It is important to note that this action expect "YAML_FINAL_PROMOTION_CONFIG_IMPORTER" already uploaded as artifact prior this action being called

name: 'Partior - Generic initialize and inject promotion variables'
description: 'Generic initialize and inject promotion variables'
inputs:
  sequence-item:  
    description: 'Item value from matrix execution while reading promotio.artifact'
    required: true
    default: ''

  yaml-importer-file:  
    description: 'Yaml importer file which contain the promotion config'
    required: false
    default: ''

  pat-token:
    description: 'PAT token to push code'
    required: false
    default: ${{ github.token }}
# outputs:
#   found-list:
#     description: "List of sequence name in array"
#     value: ${{ steps.get-sequence.outputs.list }}

runs:
  using: "composite"
  steps:
    - name: Initialize promotion variables for ${{ matrix.artifact-sequence-item }}
      id: init-variables
      run: |
        currentSequenceItem="${{ inputs.sequence-item }}"
        ARTIFACT_BASE_NAME=$(echo $currentSequenceItem | awk -F'__' '{print $1}')
        SEQUENCE_ITEM_NO=$(echo $currentSequenceItem | awk -F'__' '{print $2}')
        ARTIFACT_BASE_NAME=${ARTIFACT_BASE_NAME}
        YAML_FINAL_PROMOTION_CONFIG_IMPORTER=yaml_final_promotion_config_importer_${ARTIFACT_BASE_NAME}_${{ github.run_id }}_${{ github.run_number }}
        if [[ ! -z "${{ inputs.yaml-importer-file }}" ]]; then
          YAML_FINAL_PROMOTION_CONFIG_IMPORTER="${{ inputs.yaml-importer-file }}"
        fi

        # echo SMC_NAME=${SMC_NAME} >> $GITHUB_ENV
        echo "SEQUENCE_ITEM_NO=${SEQUENCE_ITEM_NO}" >> $GITHUB_ENV
        echo "ARTIFACT_BASE_NAME=${ARTIFACT_BASE_NAME}" >> $GITHUB_ENV
        echo "YAML_FINAL_PROMOTION_CONFIG_IMPORTER=${YAML_FINAL_PROMOTION_CONFIG_IMPORTER}" >> $GITHUB_ENV
        echo "YAML_FINAL_PROMOTION_CONFIG_IMPORTER=${YAML_FINAL_PROMOTION_CONFIG_IMPORTER}" | tee -a $GITHUB_OUTPUT

        # echo [INFO] SMC_NAME=${SMC_NAME}
        echo [INFO] SEQUENCE_ITEM_NO=${SEQUENCE_ITEM_NO}
        echo [INFO] ARTIFACT_BASE_NAME=${ARTIFACT_BASE_NAME}
        echo [INFO] YAML_FINAL_PROMOTION_CONFIG_IMPORTER=${YAML_FINAL_PROMOTION_CONFIG_IMPORTER}
      shell: bash

    - name: Download Final Promotion importer
      uses: actions/download-artifact@v4
      with:
        name: ${{ steps.init-variables.outputs.YAML_FINAL_PROMOTION_CONFIG_IMPORTER }}

    - name: Start import Final Promotion config
      id: final-promotion-config
      run: |
        echo Importing ...${{ steps.init-variables.outputs.YAML_FINAL_PROMOTION_CONFIG_IMPORTER }}
        source ./${{ steps.init-variables.outputs.YAML_FINAL_PROMOTION_CONFIG_IMPORTER }}
      shell: bash

    - uses: actions/checkout@v4
      with:
        repository: "${{ github.repository }}"
        token: "${{ inputs.pat-token }}"
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: ${{ github.ref }}

    - name: Get artifacts details for promotion
      run: ${{ github.action_path }}/../../scripts/generic-init-promotion-vars-get-artifacts-details.sh
      shell: bash

    - name: Get git storing details
      run: ${{ github.action_path }}/../../scripts/generic-init-promotion-vars-get-store-git-details.sh
      shell: bash
      
    - name: Set jfrog path
      run: |
        set +e
        function failIfEmpty() {
            local inputKey="$1"
            local inputKeyValue=${!inputKey}
            if [[ -z "$inputKeyValue" ]]; then
                echo "[ERROR] Key is undefined: $inputKey"
                exit 1
            fi
        }
        ## Throw error if not set
        failIfEmpty "FINAL_ARTIFACT_BASE_NAME"
        failIfEmpty "FINAL_ARTIFACT_GROUP"
        failIfEmpty "FINAL_ARTIFACT_SRC_REPO"
        failIfEmpty "FINAL_ARTIFACT_PROMO_REPO"
        failIfEmpty "FINAL_ARTIFACT_TYPE"
        failIfEmpty "FINAL_ARTIFACT_SRC_VERSION"
        failIfEmpty "FINAL_ARTIFACT_RELEASE_VERSION"
        failIfEmpty "FINAL_ARTIFACT_SRC_PACKAGE_NAME"
        failIfEmpty "FINAL_ARTIFACT_RELEASE_PACKAGE_NAME"

        ## Set source path
        artifactSourceFullPath=${FINAL_ARTIFACT_SRC_REPO}/${FINAL_ARTIFACT_GROUP}/${FINAL_ARTIFACT_BASE_NAME}/${FINAL_ARTIFACT_SRC_PACKAGE_NAME}
        echo FINAL_ARTIFACT_SOURCE_FULL_PATH="${artifactSourceFullPath}" >> $GITHUB_ENV

        ## Set target release path
        artifactReleaseFullPath=${FINAL_ARTIFACT_PROMO_REPO}/${FINAL_ARTIFACT_GROUP}/${FINAL_ARTIFACT_BASE_NAME}/${FINAL_ARTIFACT_RELEASE_PACKAGE_NAME}
        echo FINAL_ARTIFACT_RELEASE_FULL_PATH="${artifactReleaseFullPath}" >> $GITHUB_ENV
      shell: bash

    - name: Show retrieved details
      run: |
        echo [INFO] Listing...
        echo [INFO] YAML_ARTIFACT_FILE="${YAML_ARTIFACT_FILE}"
        echo [INFO] YAML_VERSION_QUERY_PATH="${YAML_VERSION_QUERY_PATH}"
        echo [INFO] FINAL_ARTIFACT_SRC_VERSION="${FINAL_ARTIFACT_SRC_VERSION}"
        echo [INFO] FINAL_ARTIFACT_RELEASE_VERSION="${FINAL_ARTIFACT_RELEASE_VERSION}"
        echo [INFO] FINAL_ARTIFACT_SRC_PACKAGE_NAME="${FINAL_ARTIFACT_SRC_PACKAGE_NAME}"
        echo [INFO] FINAL_ARTIFACT_RELEASE_PACKAGE_NAME="${FINAL_ARTIFACT_RELEASE_PACKAGE_NAME}"
        echo [INFO] FINAL_ARTIFACT_BASE_NAME="${FINAL_ARTIFACT_BASE_NAME}"
        echo [INFO] FINAL_ARTIFACT_GROUP="${FINAL_ARTIFACT_GROUP}"
        echo [INFO] FINAL_ARTIFACT_SRC_REPO="${FINAL_ARTIFACT_SRC_REPO}"
        echo [INFO] FINAL_ARTIFACT_PROMO_REPO="${FINAL_ARTIFACT_PROMO_REPO}"
        echo [INFO] FINAL_ARTIFACT_TYPE="${FINAL_ARTIFACT_TYPE}"
        echo [INFO] FINAL_ARTIFACT_SOURCE_FULL_PATH="${FINAL_ARTIFACT_SOURCE_FULL_PATH}"
        echo [INFO] FINAL_ARTIFACT_RELEASE_FULL_PATH="${FINAL_ARTIFACT_RELEASE_FULL_PATH}"
        echo [INFO] STORE_VERSION_ENABLE="${STORE_VERSION_ENABLE}"
        echo [INFO] STORE_VERSION_GIT_ENABLE="${STORE_VERSION_GIT_ENABLE}"
        echo [INFO] STORE_VERSION_GIT_REPO="${STORE_VERSION_GIT_REPO}"
        echo [INFO] STORE_VERSION_GIT_STORE_KEY="${STORE_VERSION_GIT_STORE_KEY}"
        echo [INFO] STORE_VERSION_GIT_TARGET_ENV_FILE="${STORE_VERSION_GIT_TARGET_ENV_FILE}"
        echo [INFO] JIRA_VERSION_IDENTIFIER="${JIRA_VERSION_IDENTIFIER}"
        echo [INFO] JIRA_PROJECT_KEY="${JIRA_PROJECT_KEY}"
      shell: bash

    - run: echo [INFO] Done injecting...
      shell: bash
