name: 'Partior - Store version as config in Git'
description: 'Store version as config in Git'
inputs:
  yaml-store-path-key:
    description: 'Query Path to the stored configuration'
    required: true
    default: ''
  yaml-env-list-query-path:
    description: 'Query Path to the list of env'
    required: false
    default: artifact.packager.store-version.git.target-envs
  target-yaml-config-file:  
    description: 'Target yaml config to be updated'
    required: true
    default: ''
  create-if-new-config:  
    description: 'Create new file if target yaml file not found'
    required: false
    default: true
  target-repo:  
    description: 'Target repo where yaml is stored'
    required: true
    default: ''
  target-repo-ref:  
    description: 'Target repo ref to be updated'
    required: false
    default: 'main'
  artifact-base-name:  
    description: 'Artifact base name to be stored in yaml'
    required: true
    default: ''
  artifact-version:  
    description: 'Artifact version to be stored in yaml'
    required: true
    default: ''
  git-push:
    description: 'Flag to indicate if git push to be executed'
    required: false
    default: true
  pat-token:
    description: 'PAT token to push code'
    required: true
    default: ''
  search-list-match-value:
    description: 'Used only during list searching. Matching value from the object @@FOUND@@'
    required: false
    default: ''
  search-list-yaml-post-query:
    description: 'Used only during list searching. Must contain @@SEARCH@@ as list object reference'
    required: false
    default: ''
  target-multi-yaml-config-files:  
    description: 'Additional yaml files to be updated. Support comma delimited.'
    required: false
    default: ''
  strict-update:  
    description: 'If true, will fail if updating failed'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    # - run: |
    #     echo Listing env...
    #     set
    #   shell: bash

    - uses: actions/checkout@v4
      with:
        repository: ${{ inputs.target-repo }}
        token: ${{ inputs.pat-token }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: ${{ inputs.target-repo-ref }}

    - name: convert yaml to props config
      run: |
        ${{ github.action_path }}/../../scripts/generic-store-version-as-config-in-git.sh \
          "${{ inputs.yaml-store-path-key }}" \
          "${{ inputs.yaml-env-list-query-path }}" \
          "${{ inputs.target-yaml-config-file }}" \
          "${{ inputs.artifact-base-name }}" \
          "${{ inputs.artifact-version }}" \
          "${{ inputs.target-repo }}" \
          "${{ inputs.create-if-new-config }}" \
          "${{ inputs.pat-token }}" \
          "${{ inputs.search-list-match-value }}" \
          "${{ inputs.search-list-yaml-post-query }}" \
          "${{ inputs.target-multi-yaml-config-files }}" \
          "${{ inputs.strict-update }}"
      shell: bash
       
    - name: Push changes
      if: inputs.git-push == 'true'
      uses: partior-libs/gjs-github-push@partior-stable
      with:
        repository: ${{ inputs.target-repo }}
        github_token: ${{ inputs.pat-token }}
        branch: ${{ inputs.target-repo-ref }}

    - run: echo Done storing version
      shell: bash
