name: 'Partior - Consolidate mapped SMC addresses for PCTL'
description: 'Consolidate mapped SMC addresses for PCTL'
inputs:
  target-yql-write-base:  
    description: 'Target Yaml Query Path to be written'
    required: true
    default: ''
  target-smc-yml-filename:
    description: 'Filename (without path) of smc yaml to be written/created'
    required: true
    default: 'smc.yml'
  commonconfig-dir:  
    description: 'Path to commonconfig'
    required: true
    default: 'commonconfig'
  source-smc-basedir:  
    description: 'Base dir of the checkedout smc repo'
    required: true
    default: 'smc-tmp/config'
  smc-workspace:  
    description: 'Path of checkedout smc config repo'
    required: true
    default: 'smc-tmp'
  yaml-maps-query-path:  
    description: 'Yaml query path to read from controller config for the KV maps value'
    required: false
    default: 'artifact-commonconfig.smc-address-file.maps'
runs:
  using: "composite"
  steps:
    - name: convert yaml to props config
      run: |
        ${{ github.action_path }}/../../scripts/smc-consolidate-addresses-for-pctl.sh \
          "${{ inputs.target-yql-write-base }}" \
          "${{ inputs.target-smc-yml-filename }}" \
          "${{ inputs.commonconfig-dir }}" \
          "${{ inputs.source-smc-basedir }}" \
          "${{ inputs.smc-workspace }}" \
          "${{ inputs.yaml-maps-query-path }}"
      shell: bash

    - run: echo Done processing SMC addresses
      shell: bash
