name: 'Partior - Retrieve and store selected key value pair into Git'
description: 'Retrieve and store selected key value pair into Git in vanilla format'
inputs:
  contract-addresses-props-file:
    description: 'Path to the prop config file which contain the contract addresses'
    required: true
    default: 'contract-summary.conf'
  env-name:  
    description: 'Target environment name that is deployed'
    required: true
    default: ''
  store-config-query-list:  
    description: 'Query Path to the stored configuration. Can be comma delimited'
    required: false
    default: 'contract-addresses.extract-by-log.store.selection-to-git,contract-addresses.extract-all.store.selection-to-git'
  git-push:
    description: 'Flag to indicate if git push to be executed'
    required: false
    default: true
  target-repo:  
    description: 'Target repo where yaml is stored'
    required: true
    default: ''
  target-repo-ref:  
    description: 'Target repo ref to be updated'
    required: false
    default: 'main'
  pat-token:
    description: 'PAT token to push code'
    required: true
    default: ''
outputs:
  generated-filename:
    description: "Filename of the converted config script"
    value: ${{ inputs.output-file }}
runs:
  using: "composite"
  steps:
    - run: |
        echo Listing env...
        set
      shell: bash

    - name: convert yaml to props config
      run: |
        ${{ github.action_path }}/../../scripts/smc-store-selection-addresses-to-git.sh \
          "${{ inputs.store-config-query-list }}" \
          "${{ inputs.contract-addresses-props-file }}" \
          "${{ inputs.env-name }}" \
          "${{ inputs.target-repo }}" \
          "${{ inputs.pat-token }}"
      shell: bash
       
    - name: Push changes
      if: inputs.git-push == 'true'
      uses: partior-libs/gjs-github-push@partior-stable
      with:
        repository: ${{ inputs.target-repo }}
        github_token: ${{ inputs.pat-token }}
        branch: ${{ inputs.target-repo-ref }}

    - run: echo Done storing SMC addresses...
      shell: bash
