name: 'Partior - Get numeric ordering sequence in JSON array obtained from YAML '
description: 'Get numeric ordering sequence in JSON array obtained from YAML. Useful for matrix execution.'
inputs:
  yaml-file:  
    description: 'Yaml query path to the sequence list. Skip this if already injected into env'
    required: false
    default: ''

  yaml-path-to-config:  
    description: 'Yaml query path to the sequence list'
    required: true
    default: ''

  prepend-identifier:  
    description: 'Prepend the identifider to the numeric sequence. Useful for sub-matrix execution.'
    required: false
    default: ''

outputs:
  found-list:
    description: "List of sequence name in array"
    value: ${{ steps.get-sequence.outputs.list }}

runs:
  using: "composite"
  steps:
    - name: Extract query path
      run: |
        fullQueryPath=${{ inputs.yaml-path-to-config }}
        parentPath="${fullQueryPath%.*}"
        listPath="${fullQueryPath##*.}"
        echo PARENT_QUERY_PATH=${parentPath} >> $GITHUB_ENV
        echo LIST_QUERY_PATH=${listPath} >> $GITHUB_ENV
        echo YAML_IMPORTER_FILE=yaml_importer_${{ github.run_id }}_${{ github.run_number }} >> $GITHUB_ENV
      shell: bash

    - name: Generate YAML Importer
      if: inputs.yaml-file != ''
      uses: partior-libs/gcs-yaml-importer@partior-stable
      with:
        yaml-file: ${{ inputs.yaml-file }}
        query-path: ${{ env.PARENT_QUERY_PATH }}
        output-file: ${{ env.YAML_IMPORTER_FILE }}

    - name: Start import config
      if: inputs.yaml-file != ''
      id: yaml-config
      run: |
        echo Importing ...${{ env.YAML_IMPORTER_FILE }}
        source ./${{ env.YAML_IMPORTER_FILE }}
      shell: bash  
        
    - id: get-sequence
      run: |
        ${{ github.action_path }}/../../scripts/generic-get-yaml-list-count-in-json-sequence.sh \
          "${{ env.LIST_QUERY_PATH }}" \
          "${{ inputs.prepend-identifier }}"
      shell: bash

    - run: echo [INFO] Done converting...
      shell: bash

