name: 'Partior - Merge a release PR'
description: 'Merge a release PR. This action should be triggered during promotion stage'
inputs:
  target-repo:  
    description: 'Repository name of the PR'
    required: true
    default: ''

  pull-request-number:
    description: 'PR number to be merged'
    required: true
    default: ''

  qualified-src-branches:
    description: 'Branches which allowed to be source of the PR. Support comma delimited'
    required: false
    default: 'release'

  qualified-target-branches:
    description: 'Branches which allowed to be target of the PR. Support comma delimited'
    required: false
    default: 'main,master'

  pat-token:  
    description: 'GitHub PAT Token to perform the merge'
    required: true
    default: ''

outputs:
  qualified:
    description: "Return check result if artifact can be promoted. true/false"
    value: ${{ steps.promotion.outputs.valid-result }}

runs:
  using: "composite"

  steps:
    - name: Login with GH cli
      run: |
        set +e
          echo ${{ inputs.pat-token }} > passw.txt
          gh version
          gh auth login --with-token < passw.txt
      shell: bash

    ## After validating, it will generate env variable SOURCE_MERGE_BRANCH and TARGET_MERGE_BRANCH 
    - name: Check PR if can proceed merge
      run: ${{ github.action_path }}/../../scripts/generic-validate-pr-status.sh "${{ inputs.target-repo }}" "${{ inputs.pull-request-number }}" "${{ inputs.qualified-src-branches }}" "${{ inputs.qualified-target-branches }}"
      shell: bash

    - uses: actions/checkout@v3
      with:
        repository: "${{ inputs.target-repo }}"
        token: ${{ inputs.pat-token }}
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
        ref: ${{ env.TARGET_MERGE_BRANCH }}

    - name: Merge PR
      run: |
        echo [INFO] Start merging...
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git remote set-url origin https://${{ inputs.pat-token }}@github.com/${{ inputs.target-repo }}
        git checkout ${SOURCE_MERGE_BRANCH}
        git pull
        git checkout ${TARGET_MERGE_BRANCH}
        git merge ${SOURCE_MERGE_BRANCH} --ff-only -m "[Bot] Auto merged"
        echo [INFO] Merging completed locally...
      shell: bash

    - name: Push changes
      uses: partior-libs/gjs-github-push@partior-stable
      with:
        github_token: ${{ inputs.pat-token }}
        repository: "${{ inputs.target-repo }}"
        branch: ${{ env.TARGET_MERGE_BRANCH }}

        
    - run: echo [INFO] Done merging...
      shell: bash

