name: test-store-generic-git-tag
on:
  push:
    paths:
      - 'actions/generic-git-tag/**'
      - 'scripts/generic-git-tag.sh'
      - '.github/workflows/unit-test-generic-git-tag.yml'
  workflow_dispatch:

jobs:
  test-scenario-1-start:
    runs-on: ubuntu-latest
    steps:
      - name: Start tag
        uses: partior-libs/gcs-pipe-utils/actions/generic-git-tag@main
        with: 
          target-repo: ${{ github.repository }}
          artifact-version: "9.9.9-test-version"
          target-repo-ref: 215d4067632e850852a5ca9f605579a111b34bc1
          pat-token: ${{ secrets.REPO_PAT }}


