name: test-override-prop-conf

on:
  push:
    paths:
      - 'actions/generic-override-prop-conf/**'
      - 'scripts/generic-override-prop-conf.sh'
      - '.github/workflows/unit-test-generic-override-prop-conf.yml'
  workflow_dispatch:

env:
  SU_CD_CONFIG_IMPORTER: su_cd_config_importer
  BASE_CONFIG_FILE: base_config

jobs:
  test-scenario-1-reader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Read sample SU CD config
        uses: partior-libs/gcs-yaml-importer@main
        with:
          yaml-file: unit-test-config/controller-config/smc-settlement-utility.yml
          query-path: .smc.cd.environments.dev02
          output-file: ${{ env.SU_CD_CONFIG_IMPORTER }}
          yaml-file-for-default: unit-test-config/controller-config/smc-default.yml
          query-path-for-default: .smc.cd.environments.default
          upload: true

  test-scenario-1-start:
    needs: [ test-scenario-1-reader ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Convert yaml to prop
        uses: partior-libs/gcs-pipe-utils/actions/generic-convert-yaml-to-prop@main
        with:
          yaml-file: unit-test-config/deploy-config/env/dev02.yml
          query-path: .deployment-config
          output-file: ${{ env.BASE_CONFIG_FILE }}

      - name: Override with local conf
        uses: partior-libs/gcs-pipe-utils/actions/generic-override-prop-conf@main
        with:
          base-conf-file: ${{ env.BASE_CONFIG_FILE }}
          target-conf-file: unit-test-config/project-config/project.conf

      - name: View overriden config file
        run:  |
          cat unit-test-config/project-config/project.conf