name: test-store-all-addresses-to-git

on:
  push:
    paths:
      - 'actions/smc-initial-setup-prep/**'
      - 'scripts/smc-initial-setup-prep.sh'
      - '.github/workflows/unit-test-smc-initial-setup-prep.yml'
  workflow_dispatch:

env:
  SU_CD_CONFIG_IMPORTER: su_cd_config_importer
  # TRUFFLE_CONFIG_FILE: truffle_config

jobs:
  test-scenario-1-reader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read sample SU CD config
        uses: partior-libs/gcs-yaml-importer@main
        with:
          yaml-file: unit-test-config/controller-config/smc-settlement-utility.yml
          query-path: .smc.cd.environments.dev02
          output-file: ${{ env.SU_CD_CONFIG_IMPORTER }}
          yaml-file-for-default: unit-test-config/controller-config/smc-default.yml
          query-path-for-default: .smc.cd.environments.default
          upload: true

  test-scenario-1-start:
    needs: [ test-scenario-1-reader ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.SU_CD_CONFIG_IMPORTER }}

      - name: Start import pipeline config
        id: pipeline-config
        run: |
          echo Importing ...${{ env.SU_CD_CONFIG_IMPORTER }}
          source ./${{ env.SU_CD_CONFIG_IMPORTER }}

      - name: Get sequence list
        id: sequence-list
        uses: partior-libs/gcs-pipe-utils/actions/smc-initial-setup-prep@main

      - name: View final sequence list
        run:  |
          echo [DEBUG] Found: ${{ steps.sequence-list.outputs.found-list }}