name: test-generic-check-if-artifact-already-promoted

on:
  push:
    paths:
      - 'actions/generic-check-if-artifact-already-promoted/**'
      - 'scripts/generic-curl-get-artifact-meta.sh'
      - 'scripts/common-libs.sh'
      - '.github/workflows/unit-test-generic-check-if-artifact-already-promoted.yml'
  workflow_dispatch:

jobs:
  test-scenario-1-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check release existed but different checksum
        id: artifact-1
        uses: partior-libs/gcs-pipe-utils/actions/generic-check-if-artifact-already-promoted@main
        with:
          source-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1-dev.24+bld.30.4.tgz
          # release-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1.tgz
          release-artifact-full-path: smc-generic-dev/partior/settlement-utility/settlement-utility-1.2.1-dev.52+bld.133.1.tgz
          jfrog-token: ${{ secrets.JFROG_TOKEN }}
        continue-on-error: true

      - name: Display first result
        run:  |
          echo Artifact promotion flag: [${{ steps.artifact-promoted1.outputs.promoted }}]

      - name: Fail if not empty
        if: steps.artifact-promoted1.outputs.promoted != ''
        run: |
          exit 1

      - name: Check release not existed
        id: artifact-promoted2
        uses: partior-libs/gcs-pipe-utils/actions/generic-check-if-artifact-already-promoted@main
        with:
          source-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1-dev.24+bld.30.4.tgz
          release-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1.tgz
          jfrog-token: ${{ secrets.JFROG_TOKEN }}

      - name: Display second result
        run:  |
          echo Artifact promotion flag: [${{ steps.artifact-promoted2.outputs.promoted }}]

      - name: Fail if not false
        if: steps.artifact-promoted2.outputs.promoted != 'false'
        run: |
          exit 1

      - name: Check release existed and same checksum
        id: artifact-promoted3
        uses: partior-libs/gcs-pipe-utils/actions/generic-check-if-artifact-already-promoted@main
        with:
          source-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1-dev.24+bld.30.4.tgz
          release-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1-dev.24+bld.30.4.tgz
          jfrog-token: ${{ secrets.JFROG_TOKEN }}

      - name: Display third result
        run:  |
          echo Artifact promotion flag: [${{ steps.artifact-promoted3.outputs.promoted }}]

      - name: Fail if not true
        if: steps.artifact-promoted3.outputs.promoted != 'true'
        run: |
          exit 1