name: test-generic-promote-version
on:
  push:
    paths:
      - 'actions/generic-promote-version/**'
      - '.github/workflows/unit-test-generic-promote-version.yml'
  workflow_dispatch:

jobs:
  test-scenario-1-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup jfrog
        uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ENV_1: ${{ secrets.JFROG_TOKEN }}

     # - name: Delete dummy target if present
      #  run: |
       #   jfrog rt del smc-generic-release/antz/settlement-utility/settlement-utility-1.2.1.tgz

      - name: Start promotion
        id: artifact-1
        uses: partior-libs/gcs-pipe-utils/actions/generic-promote-version@main
        with:
          source-artifact-full-path: smc-generic-dev/partior/settlement-utility/settlement-utility-1.2.1-dev.54+bld.135.1.tgz
          release-artifact-full-path: smc-generic-release-local/antz/settlement-utility/settlement-utility-1.2.1.tgz
          jfrog-token: ${{ secrets.JFROG_TOKEN }}
          final-artifact-source-version: "2.0.3-rc.7"
          final-artifact-release-version: "2.0.3"
          jira-username: ${{ secrets.JIRA_USERNAME }}
          jira-password: ${{ secrets. JIRA_PASSWORD }}
          jira-version-identifier: su
          jira-project-key: DEVPILOT
