name: test-generic-check-properties-if-artifact-can-promote

on:
  push:
    paths:
      - 'actions/generic-check-properties-if-artifact-can-promote/**'
      - 'scripts/generic-curl-get-artifact-meta.sh'
      - 'scripts/common-libs.sh'
      - '.github/workflows/unit-test-generic-check-properties-if-artifact-can-promote.yml'
  workflow_dispatch:

jobs:
  test-scenario-1-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check artifact without prop
        id: artifact-1
        uses: partior-libs/gcs-pipe-utils/actions/generic-check-properties-if-artifact-can-promote@main
        with:
          source-artifact-full-path: smc-generic-dev/partior/settlement-utility/settlement-utility-1.2.1-dev.39+bld.107.1.tgz
          jfrog-token: ${{ secrets.JFROG_TOKEN }}
        continue-on-error: true

      - name: Display first result
        run:  |
          echo Artifact promotion flag: [${{ steps.artifact-promoted1.outputs.qualified }}]

      - name: Fail if not empty
        if: steps.artifact-promoted1.outputs.qualified != ''
        run: |
          exit 1

      - name: Check artifact with prop
        id: artifact-promoted2
        uses: partior-libs/gcs-pipe-utils/actions/generic-check-properties-if-artifact-can-promote@main
        with:
          source-artifact-full-path: smc-generic-dev/partior/settlement-utility/settlement-utility-1.2.1-dev.54+bld.135.1.tgz
          jfrog-token: ${{ secrets.JFROG_TOKEN }}

      - name: Display second result
        run:  |
          echo Artifact promotion flag: [${{ steps.artifact-promoted2.outputs.qualified }}]

      - name: Fail if not true
        if: steps.artifact-promoted2.outputs.qualified != 'true'
        run: |
          exit 1
