name: test-smc-backup-build-folder

on:
  push:
    paths:
      - 'actions/smc-backup-build-folder/**'
      - 'scripts/smc-backup-build-folder.sh'
      - '.github/workflows/unit-test-smc-backup-build-folder.yml'
  workflow_dispatch:

env:
  SU_CD_CONFIG_IMPORTER: su_cd_config_importer
  LOWERCASE_TARGET_ENV: dev02
  ARTIFACT_BASE_NAME: settlement-utility
  # TRUFFLE_CONFIG_FILE: truffle_config

jobs:
  test-scenario-1-reader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read sample SU CD config
        uses: partior-libs/gcs-yaml-importer@main
        with:
          yaml-file: unit-test-config/controller-config/smc-settlement-utility.yml
          query-path: .smc.cd.environments.dev02
          output-file: ${{ env.SU_CD_CONFIG_IMPORTER }}
          yaml-file-for-default: unit-test-config/controller-config/smc-default.yml
          query-path-for-default: .smc.cd.environments.default
          upload: true

  test-scenario-1-start:
    needs: [ test-scenario-1-reader ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.SU_CD_CONFIG_IMPORTER }}

      - name: Source env file
        run: |
          source ./${{ env.SU_CD_CONFIG_IMPORTER }}

      - name: Store backup
        uses: partior-libs/gcs-pipe-utils/actions/smc-backup-build-folder@main
        with: 
          artifact-base-name: settlement-utility
          artifact-version: 9.9.9-dev.9+bld.99.9
          artifact-group: partior
          env-name: dev02
          yaml-store-file: unit-test-config/deploy-config/env/dev02_deployed_manifest.yml
          yaml-store-path-key: .packages.${{ env.ARTIFACT_BASE_NAME }}.deployed
          artifactory-repo: smc-generic-dev
          artifact-source-folder-path: project-config
          git-push: true
          artifactory-upload: false
          jfrog-token: 123

      - name: View final updated yaml 
        run:  |
          cat unit-test-config/deploy-config/env/dev02_deployed_manifest.yml

