name: test-store-selection-addresses-to-git

on:
  push:
    paths:
      - 'actions/smc-store-selection-addresses-to-git/**'
      - 'scripts/smc-store-selection-addresses-to-git.sh'
      - '.github/workflows/unit-test-smc-store-selection-addresses-to-git.yml'
  workflow_dispatch:

env:
  SU_CD_CONFIG_IMPORTER: su_cd_config_importer
  LOWERCASE_TARGET_ENV: dev02
  ARTIFACT_BASE_NAME: settlement-utility
  # TRUFFLE_CONFIG_FILE: truffle_config

jobs:
  test-scenario-1-reader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read sample SU CD config
        uses: partior-libs/gcs-yaml-importer@main
        with:
          yaml-file: unit-test-config/controller-config/smc-settlement-utility.yml
          query-path: .smc.cd.environments.dev02
          output-file: ${{ env.SU_CD_CONFIG_IMPORTER }}
          yaml-file-for-default: unit-test-config/controller-config/smc-default.yml
          query-path-for-default: .smc.cd.environments.default
          upload: true

  test-scenario-1-start:
    needs: [ test-scenario-1-reader ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.SU_CD_CONFIG_IMPORTER }}

      - name: Source env file
        run: |
          source ./${{ env.SU_CD_CONFIG_IMPORTER }}

      - name: Retrieve and store SMC addresses in Git
        uses: partior-libs/gcs-pipe-utils/actions/smc-store-selection-addresses-to-git@main
        with: 
          contract-addresses-props-file: unit-test-config/deploy-config/sample-contract-addresses.conf
          env-name: dev02
          store-config-query-list: contract-addresses.extract-by-log.store.selection-to-git,contract-addresses.extract-all.store.selection-to-git
          git-push: false

      - name: View final updated yaml 1
        run:  |
          cat ./unit-test-config/deploy-config/env/dev02.yml

      - name: View final updated yaml 2
        run:  |
          cat ./unit-test-config/deploy-config/env/dev02_deployed_manifest.yml