name: test-generic-check-if-artifact-already-promoted

on:
  push:
    paths:
      - 'actions/generic-check-if-artifact-already-promoted/**'
      - 'scripts/generic-curl-get-artifact-meta.sh'
      - 'scripts/common-libs.sh'
      - '.github/workflows/unit-test-generic-check-if-artifact-already-promoted.yml'
  workflow_dispatch:

jobs:
  test-scenario-1-start:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if artifact promoted
        id: artifact-promoted
        uses: partior-libs/gcs-pipe-utils/actions/generic-check-if-artifact-already-promoted@main
        with:
          source-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1-dev.24+bld.30.4.tgz
          release-artifact-full-path: smc-generic-dev/partior/onboarding/onboarding-0.0.1.tgz
          jfrog-token: ${{ secrets.JFROG_TOKEN }}

      - name: Display result
        run:  |
          echo Artifact promotion flag: [${{ steps.artifact-promoted.outputs.promoted }}]